// Code generated by gobind. DO NOT EDIT.

// Java class pkg.Pkg is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/lintang-b-s/Navigatorx/pkg
package pkg;

import go.Seq;

public abstract class Pkg {
	static {
		Seq.touch(); // for loading the native library
		_init();
	}
	
	private Pkg() {} // uninstantiable
	
	// touch is called from other bound packages to initialize this package
	public static void touch() {}
	
	private static native void _init();
	
	
	public static final double ALTERNATIVE_ROUTE_SIMILARITY_THRESHOLD = 92;
	// skipped const BICYCLE with unsupported type: github.com/lintang-b-s/Navigatorx/pkg.VehicleTypeT
	
	// skipped const BUS with unsupported type: github.com/lintang-b-s/Navigatorx/pkg.VehicleTypeT
	
	// skipped const BUS_GUIDEWAY with unsupported type: github.com/lintang-b-s/Navigatorx/pkg.OsmHighwayType
	
	// skipped const CYCLEWAY with unsupported type: github.com/lintang-b-s/Navigatorx/pkg.OsmHighwayType
	
	public static final boolean DEBUG = false;
	public static final double DUMMY_EDGE_LENGTH = 1;
	// skipped const FERRY with unsupported type: github.com/lintang-b-s/Navigatorx/pkg.OsmHighwayType
	
	// skipped const FOOT with unsupported type: github.com/lintang-b-s/Navigatorx/pkg.VehicleTypeT
	
	// skipped const FOOTWAY with unsupported type: github.com/lintang-b-s/Navigatorx/pkg.OsmHighwayType
	
	// skipped const GOODS with unsupported type: github.com/lintang-b-s/Navigatorx/pkg.VehicleTypeT
	
	// skipped const HGV with unsupported type: github.com/lintang-b-s/Navigatorx/pkg.VehicleTypeT
	
	public static final double INF_WEIGHT = 1e+15;
	public static final long INF_WEIGHT_INT = 1000000000000000L;
	// skipped const INVALID_HIGHWAY with unsupported type: github.com/lintang-b-s/Navigatorx/pkg.OsmHighwayType
	
	public static final double INVALID_LAT = 91;
	public static final double INVALID_LON = 181;
	// skipped const LEFT_TURN with unsupported type: github.com/lintang-b-s/Navigatorx/pkg.TurnType
	
	// skipped const LIVING_STREET with unsupported type: github.com/lintang-b-s/Navigatorx/pkg.OsmHighwayType
	
	// skipped const MINIBUS with unsupported type: github.com/lintang-b-s/Navigatorx/pkg.VehicleTypeT
	
	// skipped const MOTORCAR with unsupported type: github.com/lintang-b-s/Navigatorx/pkg.VehicleTypeT
	
	// skipped const MOTORCYCLE with unsupported type: github.com/lintang-b-s/Navigatorx/pkg.VehicleTypeT
	
	// skipped const MOTORROAD with unsupported type: github.com/lintang-b-s/Navigatorx/pkg.OsmHighwayType
	
	// skipped const MOTORWAY with unsupported type: github.com/lintang-b-s/Navigatorx/pkg.OsmHighwayType
	
	// skipped const MOTORWAY_LINK with unsupported type: github.com/lintang-b-s/Navigatorx/pkg.OsmHighwayType
	
	// skipped const NONE with unsupported type: github.com/lintang-b-s/Navigatorx/pkg.TurnType
	
	// skipped const NO_ENTRY with unsupported type: github.com/lintang-b-s/Navigatorx/pkg.TurnType
	
	// skipped const PATH with unsupported type: github.com/lintang-b-s/Navigatorx/pkg.OsmHighwayType
	
	// skipped const PEDESTRIAN with unsupported type: github.com/lintang-b-s/Navigatorx/pkg.OsmHighwayType
	
	// skipped const PRIMARY with unsupported type: github.com/lintang-b-s/Navigatorx/pkg.OsmHighwayType
	
	// skipped const PRIMARY_LINK with unsupported type: github.com/lintang-b-s/Navigatorx/pkg.OsmHighwayType
	
	// skipped const PRIVATE with unsupported type: github.com/lintang-b-s/Navigatorx/pkg.OsmHighwayType
	
	// skipped const RESIDENTIAL with unsupported type: github.com/lintang-b-s/Navigatorx/pkg.OsmHighwayType
	
	// skipped const RESIDENTIAL_LINK with unsupported type: github.com/lintang-b-s/Navigatorx/pkg.OsmHighwayType
	
	// skipped const RIGHT_TURN with unsupported type: github.com/lintang-b-s/Navigatorx/pkg.TurnType
	
	// skipped const ROAD with unsupported type: github.com/lintang-b-s/Navigatorx/pkg.OsmHighwayType
	
	// skipped const SECONDARY with unsupported type: github.com/lintang-b-s/Navigatorx/pkg.OsmHighwayType
	
	// skipped const SECONDARY_LINK with unsupported type: github.com/lintang-b-s/Navigatorx/pkg.OsmHighwayType
	
	// skipped const SERVICE with unsupported type: github.com/lintang-b-s/Navigatorx/pkg.OsmHighwayType
	
	// skipped const STEPS with unsupported type: github.com/lintang-b-s/Navigatorx/pkg.OsmHighwayType
	
	// skipped const STRAIGHT_ON with unsupported type: github.com/lintang-b-s/Navigatorx/pkg.TurnType
	
	// skipped const TAXI with unsupported type: github.com/lintang-b-s/Navigatorx/pkg.VehicleTypeT
	
	// skipped const TERTIARY with unsupported type: github.com/lintang-b-s/Navigatorx/pkg.OsmHighwayType
	
	// skipped const TERTIARY_LINK with unsupported type: github.com/lintang-b-s/Navigatorx/pkg.OsmHighwayType
	
	// skipped const TRACK with unsupported type: github.com/lintang-b-s/Navigatorx/pkg.OsmHighwayType
	
	public static final double TRAFFIC_LIGHT_ADDITIONAL_WEIGHT_SECOND = 0;
	// skipped const TRUNK with unsupported type: github.com/lintang-b-s/Navigatorx/pkg.OsmHighwayType
	
	// skipped const TRUNK_LINK with unsupported type: github.com/lintang-b-s/Navigatorx/pkg.OsmHighwayType
	
	// skipped const UNCLASSIFIED with unsupported type: github.com/lintang-b-s/Navigatorx/pkg.OsmHighwayType
	
	// skipped const UNKNOWN with unsupported type: github.com/lintang-b-s/Navigatorx/pkg.OsmHighwayType
	
	// skipped const U_TURN with unsupported type: github.com/lintang-b-s/Navigatorx/pkg.TurnType
	
	
	/**
	 * lebih dari roda dua   // see land-based transportation https://wiki.openstreetmap.org/wiki/Key:access
	 */
	public static native void setDoubleTrackedVehicleEnabled(boolean v);
	/**
	 * lebih dari roda dua   // see land-based transportation https://wiki.openstreetmap.org/wiki/Key:access
	 */
	public static native boolean getDoubleTrackedVehicleEnabled();
	
	/**
	 * vehicle or pedestrians. for oneway interperation for routing: https://wiki.openstreetmap.org/wiki/Key:onewayf
	see Land-based transportation: https://wiki.openstreetmap.org/wiki/Key:access
	vehicle is all type of vehicle (bicycle, motorcar, bus, motorcycle, hgv, goods,taxi, minibus)
	 */
	public static native void setIsVehicleEnabled(boolean v);
	/**
	 * vehicle or pedestrians. for oneway interperation for routing: https://wiki.openstreetmap.org/wiki/Key:onewayf
	see Land-based transportation: https://wiki.openstreetmap.org/wiki/Key:access
	vehicle is all type of vehicle (bicycle, motorcar, bus, motorcycle, hgv, goods,taxi, minibus)
	 */
	public static native boolean getIsVehicleEnabled();
	
	public static native void setMotorizedVehicleEnabled(boolean v);
	public static native boolean getMotorizedVehicleEnabled();
	
	public static native void setNUM_CPU(long v);
	public static native long getNUM_CPU();
	
	public static native void setProfileName(String v);
	public static native String getProfileName();
	
	// skipped variable PublicServiceVehicles with unsupported type: map[github.com/lintang-b-s/Navigatorx/pkg.VehicleTypeT]struct{}
	
	public static native void setRegionName(String v);
	public static native String getRegionName();
	
	// skipped variable VehicleType with unsupported type: github.com/lintang-b-s/Navigatorx/pkg.VehicleTypeT
	
	// skipped variable VehicleTypeTag with unsupported type: map[github.com/lintang-b-s/Navigatorx/pkg.VehicleTypeT]string
	
	public static native void setWITH_TURN_COSTS(boolean v);
	public static native boolean getWITH_TURN_COSTS();
	
	// skipped function GetHighwayType with unsupported parameter or return types
	
	// skipped function GetHighwayTypeString with unsupported parameter or return types
	
	public static native boolean getIsDoubleTrackedVehicle();
	public static native boolean getIsMotorizedVehicle();
	public static native boolean getIsVehicle();
	// skipped function GetVehicleType with unsupported parameter or return types
	
	public static native void offTurnCost();
	public static native void onTurnCost();
}
